[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cos_pricing"
version = "0.1.0"
description = "Implementation of the Fang-Oosterlee COS method for European option pricing"
authors = [
    {name = "Alick Zhou"},
    {name = "Erce Erez"},
    {name = "Michael Bakshandeh"},
    {name = "Tanay Kane"}
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "numba",
    "matplotlib"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
